# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Send notification on matrix
      env:
        MATRIX_URL: ${{ secrets.MATRIX_URL }}
        MATRIX_USER: ${{ secrets.MATRIX_USER }}
        MATRIX_PASSWORD: ${{ secrets.MATRIX_PASSWORD }}
        MATRIX_ROOM: ${{ secrets.MATRIX_ROOM }} 
      run: |
        echo "Getting access token..."
        export ACCESS_TOKEN=`jq -r '.access_token' <<< $(curl -fsb -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"identifier":{"type":"m.id.user","user":"$MATRIX_USER"},"initial_device_display_name": "Autobot","password":"$MATRIX_PASSWORD","type":"m.login.password" }' '$MATRIX_URL/_matrix/client/r0/login')`
        echo $ACCESS_TOKEN
        echo "Generating an ID..."
        export ID=$(uuidgen)
        echo $ID
        echo "Notifying Matrix room..."
        curl -f -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"body":"Le repo a été mis à jour !","format":"org.matrix.custom.html","formatted_body":"<b>Le <a href=\"https://github.com/RValeye/RT\">repo</a> a été mis à jour !</b>","msgtype": "m.text"}' '$MATRIX_URL/_matrix/client/r0/rooms/$MATRIX_ROOM/send/m.room.message/$ID?access_token=$ACCESS_TOKEN'
